// export default () => (
//   [
//     {
//        "id":19531,
//        "name":"Betasso Link Access",
//        "description":"",
//        "created_at":"2015-03-12T18:10:13.883Z",
//        "updated_at":"2017-11-10T02:13:56.849Z",
//        "distance_in_meters":7078,
//        "closest_transit_stop":{
//           "distance_to_transit_stop":670.706630807,
//           "agency":{
//              "name":"Regional Transportation District",
//              "url":"http://rtd-denver.com"
//           },
//           "stop":{
//              "id":"25783",
//              "code":null,
//              "name":"Hwy 119 & Chapman Dr",
//              "location":{
//                 "type":"Point",
//                 "coordinates":[
//                    -105.325953,
//                    40.009307
//                 ]
//              }
//           }
//        },
//        "geometry":{
//           "type":"Point",
//           "coordinates":[
//              -105.333300303612,
//              40.0071701804137
//           ]
//        },
//        "trailhead_attributes":[
//           {
//              "attribute":{
//                 "id":1,
//                 "name":"Restrooms"
//              },
//              "value":"no"
//           },
//           {
//              "attribute":{
//                 "id":null,
//                 "name":"Parking"
//              },
//              "value":"no"
//           },
//           {
//              "attribute":{
//                 "id":4,
//                 "name":"Kiosk"
//              },
//              "value":"no"
//           }
//        ],
//        "trip_ids":[
//
//        ],
//        "organization_ids":[
//           4154
//        ],
//        "_links":{
//           "self":"https://api.outerspatial.com/v0/trailheads/19531",
//           "organizations":"https://api.outerspatial.com/v0/trailheads/19531/organizations",
//           "trails":"https://api.outerspatial.com/v0/trailheads/19531/trails",
//           "trail_segments":"https://api.outerspatial.com/v0/trailheads/19531/trail_segments"
//        }
//     },
//     {
//          "id":19518,
//          "name":"Betasso Trailhead East",
//          "description":"",
//          "created_at":"2015-03-12T18:10:10.979Z",
//          "updated_at":"2017-11-10T02:13:56.849Z",
//          "distance_in_meters":7842,
//          "closest_transit_stop":{
//             "distance_to_transit_stop":1317.055376302,
//             "agency":{
//                "name":"Regional Transportation District",
//                "url":"http://rtd-denver.com"
//             },
//             "stop":{
//                "id":"20306",
//                "code":null,
//                "name":"Hwy 119 & Fourmile Cnyn Rd",
//                "location":{
//                   "type":"Point",
//                   "coordinates":[
//                      -105.325572,
//                      40.015194
//                   ]
//                }
//             }
//          },
//          "geometry":{
//             "type":"Point",
//             "coordinates":[
//                -105.340980737535,
//                40.0157676370432
//             ]
//          },
//          "trailhead_attributes":[
//             {
//                "attribute":{
//                   "id":1,
//                   "name":"Restrooms"
//                },
//                "value":"no"
//             },
//             {
//                "attribute":{
//                   "id":null,
//                   "name":"Parking"
//                },
//                "value":"yes"
//             },
//             {
//                "attribute":{
//                   "id":4,
//                   "name":"Kiosk"
//                },
//                "value":"yes"
//             }
//          ],
//          "trip_ids":[
//
//          ],
//          "organization_ids":[
//             4154
//          ],
//          "_links":{
//             "self":"https://api.outerspatial.com/v0/trailheads/19518",
//             "organizations":"https://api.outerspatial.com/v0/trailheads/19518/organizations",
//             "trails":"https://api.outerspatial.com/v0/trailheads/19518/trails",
//             "trail_segments":"https://api.outerspatial.com/v0/trailheads/19518/trail_segments"
//          }
//       },
//       {
//          "id":18254,
//          "name":"North Fork Shanahan at Lehigh",
//          "description":"",
//          "created_at":"2014-09-29T16:25:26.188Z",
//          "updated_at":"2017-11-10T02:13:56.849Z",
//          "distance_in_meters":7056,
//          "closest_transit_stop":{
//             "distance_to_transit_stop":17.019587156,
//             "agency":{
//                "name":"Regional Transportation District",
//                "url":"http://rtd-denver.com"
//             },
//             "stop":{
//                "id":"20078",
//                "code":null,
//                "name":"Lehigh St & Lafayette Dr",
//                "location":{
//                   "type":"Point",
//                   "coordinates":[
//                      -105.258547,
//                      39.967421
//                   ]
//                }
//             }
//          },
//          "geometry":{
//             "type":"Point",
//             "coordinates":[
//                -105.258643638004,
//                39.9672869607443
//             ]
//          },
//          "trailhead_attributes":[
//             {
//                "attribute":{
//                   "id":1,
//                   "name":"Restrooms"
//                },
//                "value":"no"
//             },
//             {
//                "attribute":{
//                   "id":null,
//                   "name":"Parking"
//                },
//                "value":"no"
//             },
//             {
//                "attribute":{
//                   "id":4,
//                   "name":"Kiosk"
//                },
//                "value":"yes"
//             }
//          ],
//          "trip_ids":[
//
//          ],
//          "organization_ids":[
//             3899
//          ],
//          "_links":{
//             "self":"https://api.outerspatial.com/v0/trailheads/18254",
//             "organizations":"https://api.outerspatial.com/v0/trailheads/18254/organizations",
//             "trails":"https://api.outerspatial.com/v0/trailheads/18254/trails",
//             "trail_segments":"https://api.outerspatial.com/v0/trailheads/18254/trail_segments"
//          }
//       },
//       {
//          "id":18253,
//          "name":"Cottonwood at Jay Rd",
//          "description":"",
//          "created_at":"2014-09-29T16:25:25.918Z",
//          "updated_at":"2017-11-10T02:13:56.849Z",
//          "distance_in_meters":6900,
//          "closest_transit_stop":{
//             "distance_to_transit_stop":5.85103974,
//             "agency":{
//                "name":"Regional Transportation District",
//                "url":"http://rtd-denver.com"
//             },
//             "stop":{
//                "id":"14648",
//                "code":null,
//                "name":"Jay Rd & Hwy 119",
//                "location":{
//                   "type":"Point",
//                   "coordinates":[
//                      -105.230082,
//                      40.051003
//                   ]
//                }
//             }
//          },
//          "geometry":{
//             "type":"Point",
//             "coordinates":[
//                -105.230135476657,
//                40.0509700173612
//             ]
//          },
//          "trailhead_attributes":[
//             {
//                "attribute":{
//                   "id":1,
//                   "name":"Restrooms"
//                },
//                "value":"no"
//             },
//             {
//                "attribute":{
//                   "id":null,
//                   "name":"Parking"
//                },
//                "value":"no"
//             },
//             {
//                "attribute":{
//                   "id":4,
//                   "name":"Kiosk"
//                },
//                "value":"yes"
//             }
//          ],
//          "trip_ids":[
//
//          ],
//          "organization_ids":[
//             3899
//          ],
//          "_links":{
//             "self":"https://api.outerspatial.com/v0/trailheads/18253",
//             "organizations":"https://api.outerspatial.com/v0/trailheads/18253/organizations",
//             "trails":"https://api.outerspatial.com/v0/trailheads/18253/trails",
//             "trail_segments":"https://api.outerspatial.com/v0/trailheads/18253/trail_segments"
//          }
//       }
//   ]
// )
